# Base for running docker

volumes:
  odoo_data:
  postgres_odoo:

services:
  odoo:
    build:
      context: .
      args:
        ODOO_VERSION: ${ODOO_VERSION}
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    env_file: .env
    environment:
      PGHOST: db
      PGPORT: 5432
      # for web
      #DEBUGPY_ENABLE: 0
      ODOO_PROXY_MODE: 1
      ODOO_WORKERS: 2
      ODOO_X_SENDFILE: 1
    restart: unless-stopped
    ports:
      - "8069"
      - "8072"
      - "41234"
    volumes:
      - odoo_data:/var/lib/odoo
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - postgres_odoo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      PGDATA: /var/lib/postgresql/data

  web:
    image: nginx:bookworm
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - odoo_data:/var/lib/odoo:ro
    depends_on:
      - odoo
