# Base for running docker

volumes:
  odoo_data:
  postgres_odoo:

services:
  odoo:
    build:
      context: .
      args:
        ODOO_VERSION: ${ODOO_VERSION}
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    env_file: .env
    environment:
      PGHOST: db
      PGPORT: 5432
    restart: unless-stopped
    ports:
      - "8069"
      - "8072"
      - "41234"
    volumes:
      - odoo_data:${ODOO_DATA_DIR}
    command: ["odoo-bin", "--dev", "xml"]
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - postgres_odoo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      PGDATA: /var/lib/postgresql/data
