name: Docker build and push
# with secret.SSH_KEY
# required for enterprise checkout

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # run after official build (which is Friday evening)
    - cron: '50 4 * * 6'

permissions:
  contents: read
  packages: write

concurrency:
  # cancel already in progress jobs
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        odoo-version: ["16.0"]
    env:
      ODOO_VERSION: "${{ matrix.odoo-version }}"
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup SSH Keys and known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_KEY }}"
        (ssh -T git@github.com 2>&1|| true) | grep successfully

    - name: Build Odoo Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.enterprise
        target: enterprise
        build-args: |
          ODOO_VERSION=${{ env.ODOO_VERSION }}
          ODOO_SOURCE=git@github.com:odoo
        ssh: default=${{ env.SSH_AUTH_SOCK }}
        tags: ghcr.io/${{ github.repository }}:${{ env.ODOO_VERSION }}
        push: ${{ github.event_name != 'pull_request' }}
