#!/bin/bash
case "${1:-}" in
"")
	echo "Usage: $0 module1,module2 ...options"
	exit 1
	;;
-*)
	modules=''
	;;
*/*)
	modules="$(odoo-getaddons.py "$1" -m 3)"
	echo "Modules: $modules"
	shift;;
*)
	modules=$1
	shift;;
esac

# install (if not there yet) and update (if already installed)
exec odoo --no-http --workers=0 --stop-after-init -i "$modules" -u "$modules" "$@"
