#!/bin/bash
# Run odoo and update a module list
update_switch="-u"
case "${1:-}" in
""|-h)
	echo "Usage: $0 module1,module2 [--install] ...options"
	echo
	echo "Just run odoo with installation options."
	echo "Modules can be a list of modules or a path where to find addons."
	echo "  --install indicates to install instead of update"
	exit 1
	;;
--install|-i)
	shift
	update_switch="-i"
	;;
esac
case "${1:-}" in
-*)
	modules=''
	;;
*/*)
	modules="$(odoo-getaddons.py "$1" -m 3)"
	echo "Modules: $modules"
	shift;;
*)
	modules=$1
	shift;;
esac

# install or update the modules
exec odoo-bin --no-http --workers=0 --stop-after-init $update_switch "$modules" "$@"
